//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Movies_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Movies_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\6\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\6\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
  
    ViewBag.Title = "Index";
    bool writeAccess = (bool)MoviesDBManager.Models.OnlineUsers.Write_Access();


#line default
#line hidden

#line 3 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\6\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
    if (writeAccess)
    {
        

#line default
#line hidden

#line 4 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\6\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
             __o = Helper.IconCmd("Movies", "Create", "fa-plus-square", "Ajouter...");


#line default
#line hidden

#line 5 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\6\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
                                                                                          
    }
    else
    {
        

#line default
#line hidden

#line 6 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\6\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
                      
    }

#line default
#line hidden
DefineSection("Scripts", () => {


#line 7 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\6\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
                                    __o = Url.Action("Movies");


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Movies_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Movies_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\4\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\4\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
  
    ViewBag.Title = "Index";
    bool writeAccess = (bool)MoviesDBManager.Models.OnlineUsers.Write_Access();


#line default
#line hidden

#line 3 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\4\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
    if (writeAccess)
    {
        

#line default
#line hidden

#line 4 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\4\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
             __o = Helper.IconCmd("Movies", "Create", "fa-plus-square", "Ajouter...");


#line default
#line hidden

#line 5 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\4\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
                                                                                          
    }
    else
    {
        

#line default
#line hidden

#line 6 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\4\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
                      
    }

#line default
#line hidden
DefineSection("Scripts", () => {


#line 7 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\4\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
                                    __o = Url.Action("Movies");


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\3\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\3\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
  
    ViewBag.Title = "Index";
    bool writeAccess = (bool)MoviesDBManager.Models.OnlineUsers.Write_Access();


#line default
#line hidden

#line 3 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\3\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
    if (writeAccess)
    {
        

#line default
#line hidden

#line 4 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\3\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
             __o = Helper.IconCmd("Movies", "Create", "fa-plus-square", "Ajouter...");


#line default
#line hidden

#line 5 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\3\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
                                                                                          
    }
    else
    {
        

#line default
#line hidden

#line 6 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\3\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
                      
    }

#line default
#line hidden
DefineSection("Scripts", () => {


#line 7 "C:\Users\kev\AppData\Local\Temp\85A47E895265B4063CF484C9593C769365C1\3\MoviesDBManager-Auth-master\Views\Movies\Index.cshtml"
                                    __o = Url.Action("Movies");


#line default
#line hidden
});

}
}
}
